version: '3.9'

services:
  java_app:
    container_name: db_ecommerce_application
    image: db-ecommercev1.0.0
    build: .
    ports:
     - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - java_db
  java_db:
      container_name: db_ecommerce
      image: postgres:12
      volumes:
        - pg_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: postgres
volumes:
  pg_data: